consul:
  host: localhost
  port: 8500
  discoveryHost: localhost
service:
  name: nestcloud-rbac-examples
  port: 3000
  healthCheck:
    ttl: 20
rbac:
  parameters:
    name: ${{ service.name }}-rbac
