consul:
  host: localhost
  port: 8500
  discoveryHost: localhost
  healthCheck:
    timeout: 1s
    interval: 10s
  maxRetry: 5
  retryInterval: 5000
  service:
    name: example-service
    port: 3004
rbac:
  parameters:
    key: ${{ consul.service.name }}-rbac
